import Foundation

final class ESP32Client {
    static let shared = ESP32Client()
    private let baseURL = URL(string: "http://192.168.4.1")!

    private func request(path: String, query: [URLQueryItem] = []) async throws -> Data {
        var components = URLComponents(url: baseURL.appendingPathComponent(path), resolvingAgainstBaseURL: false)!
        components.queryItems = query.isEmpty ? nil : query
        var request = URLRequest(url: components.url!)
        request.timeoutInterval = 4
        let (data, response) = try await URLSession.shared.data(for: request)
        guard let http = response as? HTTPURLResponse, 200..<400 ~= http.statusCode else {
            throw URLError(.badServerResponse)
        }
        return data
    }

    func getRoot() async throws -> String {
        String(data: try await request(path: "/"), encoding: .utf8) ?? ""
    }

    func turnOn() async throws {
        _ = try await request(path: "/on")
    }

    func turnOff() async throws {
        _ = try await request(path: "/off")
    }

    func setDateTime(day: Int, time: String) async throws {
        _ = try await request(path: "/setDataOra", query: [
            URLQueryItem(name: "giorno", value: String(day)),
            URLQueryItem(name: "orario", value: time)
        ])
    }

    func save(schedule: [DaySchedule]) async throws {
        var q: [URLQueryItem] = []
        for day in schedule {
            q += [
                URLQueryItem(name: "a\(day.id)", value: day.morning.start),
                URLQueryItem(name: "b\(day.id)", value: day.morning.end),
                URLQueryItem(name: "c\(day.id)", value: day.afternoon.start),
                URLQueryItem(name: "d\(day.id)", value: day.afternoon.end)
            ]
        }
        _ = try await request(path: "/save", query: q)
    }

    // Parses the existing HTML generated by the ESP32 firmware.
    func parseStatus(from html: String) -> ESPStatus {
        var s = ESPStatus()
        if let r = html.range(of: #"Ora attuale: <span id='ora'>([^<]+)"#, options: .regularExpression) {
            let match = String(html[r])
            s.time = match.replacingOccurrences(of: #"Ora attuale: <span id='ora'>"#, with: "", options: .regularExpression)
        }
        if html.contains("Stato filo: ON") { s.ledOn = true }
        if html.contains("Stato WiFi AP: OFF") { s.wifiOn = false }
        return s
    }
}
